#version: '27.4.0'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: linkedin
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - '3307:3306'
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - '1025:1025'
      - '8025:8025'  # Web UI for viewing emails